project:
  type: website
  output-dir: docs
website:
  navbar:
    background: "#365902"
    search: true
    left:
      - text: "Home"
        href: index.qmd

      - text: "People"
        href: people/index.qmd

      - text: "Research"
        href: research/index.qmd

      - text: "Publications"
        href: publications/index.qmd

      - text: "Courses"
        href: courses/index.qmd

      - text: "About Us"
        href: about/index.qmd
    

format:
  html:
    theme: cosmo
    linkcolor: "#365902"
    css: styles.css
    toc: true



